FROM node:20-alpine

WORKDIR /usr/src/app
ARG DATABASE_URL

COPY package.json pnpm-lock.yaml turbo.json pnpm-workspace.yaml ./

COPY ./packages ./packages
COPY ./apps/backend ./apps/backend

RUN npm i -g pnpm

RUN pnpm install
RUN ${DATABASE_URL} pnpm db:push # Ensure the database is pushed before building

RUN pnpm build:backend

EXPOSE 8000

CMD ["pnpm", "start:backend"]