FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml turbo.json pnpm-workspace.yaml ./

COPY ./packages ./packages
COPY ./apps/backend ./apps/backend

RUN npm i -g pnpm

RUN pnpm install

RUN pnpm build:backend

EXPOSE 8000

CMD ["pnpm", "start:backend"]