FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml turbo.json pnpm-workspace.yaml ./

COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend

RUN npm i -g pnpm

RUN pnpm install
RUN pnpm db:push

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "start:frontend"]