FROM node:alpine-20

WORKDIR /usr/src/app

ARG DATBASE_URL

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./turbo.json ./turbo.json
COPY ./packages ./packages

COPY ./apps/frontend ./apps/frontend

RUN npm i -g pnpm

RUN pnpm install
RUN pnpm db:push

RUN DATABASE_URL=${DATABASE_URL} pnpm run build

EXPOSE 3000

CMD ["pnpm", "start:frontend"]